on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

      - name: touch file
        run: touch hola.txt

      - name: Set text
        run: echo "Hola Mundo" > hola.txt

      - name: Read file
        run: cat hola.txt
      
  otra_tarea:
    runs-on: ubuntu-latest
    steps:
      - name: Otra Tarea
        run: echo "Esta es otra tarea"