name: variables

on: [push]

jobs:
  test_env:
    runs-on: ubuntu-latest
    
    env:
      MY_VAR: Mi variable de entorno

      
    steps:
      - name: Test
        run: |
          echo "Valor: ${{ env.MY_VAR }}"
